import { useCallback, useEffect, useState } from "react";
import { Copy, Pencil, Plus, Search, ShieldCheck, Trash2 } from "lucide-react";
import { trustHubApi,type HubPolicy,type PolicyAudit,type PolicyEvaluation } from "./trustHubApi";
const empty={name:"",description:"",domain:"messages",priority:100,conditions:{action_type:"message.send"},effect:"REQUIRE_CONFIRMATION" as const,enabled:true};
export function PolicyFirewall({token,onChanged}:{token:string;onChanged:()=>void}){const [items,setItems]=useState<HubPolicy[]>([]),[audit,setAudit]=useState<PolicyAudit[]>([]),[search,setSearch]=useState(""),[editing,setEditing]=useState<HubPolicy|null>(null),[creating,setCreating]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false),[simulation,setSimulation]=useState<PolicyEvaluation|null>(null);
 const load=useCallback(async()=>{setError("");try{const [policies,history]=await Promise.all([trustHubApi.policies(token,search),trustHubApi.policyAudit(token)]);setItems(policies);setAudit(history)}catch(e){setError(e instanceof Error?e.message:"Policies could not be loaded.")}},[token,search]);useEffect(()=>{void load()},[load]);
 async function save(form:HTMLFormElement){const data=new FormData(form),payload={name:String(data.get("name")||"").trim(),description:String(data.get("description")||"").trim(),domain:String(data.get("domain")),priority:Number(data.get("priority")),conditions:{action_type:String(data.get("action_type"))},effect:String(data.get("effect")) as HubPolicy["effect"],enabled:data.get("enabled")==="on"};if(payload.name.length<2){setError("Policy name must contain at least two characters.");return}setBusy(true);try{editing?await trustHubApi.updatePolicy(token,{...editing,...payload}):await trustHubApi.createPolicy(token,payload);setEditing(null);setCreating(false);await load();onChanged()}catch(e){setError(e instanceof Error?e.message:"Policy could not be saved.")}finally{setBusy(false)}}
 async function remove(item:HubPolicy){if(!window.confirm(`Delete “${item.name}”?`))return;try{await trustHubApi.deletePolicy(token,item.id);await load();onChanged()}catch(e){setError(e instanceof Error?e.message:"Policy could not be deleted.")}}
 async function simulate(){try{const result=await trustHubApi.evaluatePolicy(token,{domain:"messages",action_type:"message.send",context:{contact_id:"simulation"}});setSimulation(result);await load()}catch(e){setError(e instanceof Error?e.message:"Simulation failed.")}}
 const draft=editing||empty;
 return <section className="policy-firewall"><header><div><h2><ShieldCheck/> Personal Policy Firewall</h2><p>Deterministic rules enforced before controlled actions.</p></div><button type="button" onClick={()=>setCreating(true)}><Plus/> Create policy</button></header><label className="hub-search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search policies" aria-label="Search policies"/></label>{error&&<div className="hub-error" role="alert">{error}<button type="button" onClick={()=>void load()}>Retry</button></div>}
 {(creating||editing)&&<form className="hub-form" onSubmit={e=>{e.preventDefault();void save(e.currentTarget)}}><h3>{editing?"Edit policy":"Create policy"}</h3><label>Name<input name="name" defaultValue={draft.name} required minLength={2}/></label><label>Description<textarea name="description" defaultValue={draft.description}/></label><div><label>Domain<select name="domain" defaultValue={draft.domain}><option value="messages">Messages</option><option value="alarm">Alarms</option><option value="calls">Calls</option><option value="commitments">Commitments</option></select></label><label>Action<select name="action_type" defaultValue={String(draft.conditions.action_type||"message.send")}><option>message.send</option><option>alarm.create</option><option>alarm.delete</option><option>call.start</option><option>commitment.accept</option></select></label></div><div><label>Effect<select name="effect" defaultValue={draft.effect}><option value="ALLOW">Allow</option><option value="REQUIRE_CONFIRMATION">Require confirmation</option><option value="DENY">Deny</option></select></label><label>Priority<input name="priority" type="number" min="0" max="10000" defaultValue={draft.priority}/></label></div><label className="hub-check"><input name="enabled" type="checkbox" defaultChecked={draft.enabled}/> Enabled</label><footer><button type="button" onClick={()=>{setCreating(false);setEditing(null)}}>Cancel</button><button type="submit" disabled={busy}>{busy?"Saving…":"Save policy"}</button></footer></form>}
 <div className="policy-list">{items.length===0?<p className="hub-empty">No policies match this filter.</p>:items.map(item=><article key={item.id}><div><strong>{item.name}</strong><small>{item.domain} · {item.effect.replace(/_/g," ")} · priority {item.priority} · v{item.version}</small></div><span className={item.enabled?"enabled":"disabled"}>{item.enabled?"Enabled":"Disabled"}</span><button aria-label={`Edit ${item.name}`} onClick={()=>setEditing(item)}><Pencil/></button><button aria-label={`Duplicate ${item.name}`} onClick={()=>void trustHubApi.duplicatePolicy(token,item.id).then(()=>{void load();onChanged()}).catch(e=>setError(e.message))}><Copy/></button><button aria-label={`Delete ${item.name}`} onClick={()=>void remove(item)}><Trash2/></button></article>)}</div>
 <section className="policy-simulator"><h3>Policy simulator</h3><button type="button" onClick={()=>void simulate()}>Simulate message.send</button>{simulation&&<p><strong>{simulation.decision.replace(/_/g," ")}</strong> — {simulation.explanation} Matched: {simulation.matched_policy_ids.length}</p>}</section><section className="policy-audit"><h3>Evaluation history</h3>{audit.length===0?<p>No evaluations yet.</p>:audit.slice(0,10).map(row=><p key={row.id}><time>{new Date(row.created_at).toLocaleString()}</time> · {row.action_type} · <strong>{row.decision.replace(/_/g," ")}</strong></p>)}</section></section>}
