import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, BookCheck, CheckCircle2, CloudOff, FileCheck2, PauseCircle, ShieldCheck, TriangleAlert } from "lucide-react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { useAuth } from "../../contexts/AuthContext";
import { trustHubApi, type HubSummary } from "./trustHubApi";
import { PolicyFirewall } from "./PolicyFirewall";
import { TrustControls } from "./TrustControls";
import { CommitmentEscrow } from "./CommitmentEscrow";
import { LifeMap } from "./LifeMap";
import "./trustHub.css";
const tabs=["Home","Safety","Controls","Commitments","Life Map","Evidence","Offline"] as const; type Tab=typeof tabs[number];
export function TrustHubPage(){
 const {token}=useAuth(),navigate=useNavigate(),[params,setParams]=useSearchParams(); const selected=tabs.find(x=>x.toLowerCase().replace(" ","-")===params.get("tab"))||"Home";
 const [summary,setSummary]=useState<HubSummary|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{if(!token)return;setLoading(true);setError("");try{setSummary(await trustHubApi.summary(token))}catch(e){setError(e instanceof Error?e.message:"White-Space Hub could not be loaded.")}finally{setLoading(false)}},[token]); useEffect(()=>{void load()},[load]);
 const changeTab=(tab:Tab)=>setParams(tab==="Home"?{}:{tab:tab.toLowerCase().replace(" ","-")});
 const togglePause=async()=>{if(!token||!summary)return;const enabling=!summary.pause.active,reason=enabling?window.prompt("Why are you pausing AI actions?","I want to review pending actions")?.trim():"User resumed AI actions";if(!reason||!window.confirm(enabling?"Pause all nonessential AI actions now?":"Resume AI actions now?"))return;setSaving(true);setError("");try{await trustHubApi.setPause(token,{active:enabling,reason,expires_at:null});await load()}catch(e){setError(e instanceof Error?e.message:"Pause state could not be changed.")}finally{setSaving(false)}};
 const cards=summary?[["Safety policies",summary.policy_count,"Safety","Deterministic rules",<ShieldCheck/>],["Active leases",summary.active_leases,"Controls","Purpose-bound access",<CheckCircle2/>],["At-risk commitments",summary.at_risk_commitments,"Commitments","Need review",<BookCheck/>],["Pending receipts",summary.pending_receipts,"Evidence","Awaiting evidence",<FileCheck2/>],["Blocked actions",summary.blocked_actions,"Evidence","Stopped by Trust Gateway",<TriangleAlert/>],["Expiring leases",summary.expiring_leases,"Controls","Expire within seven days",<PauseCircle/>]] as const:[];
 return <main className="trust-hub"><header><button type="button" onClick={()=>navigate("/hub")} aria-label="Back to Action Hub"><ArrowLeft/></button><div><small>Governance and reliability</small><h1>White-Space Hub</h1></div><button type="button" className={summary?.pause.active?"hub-pause active":"hub-pause"} onClick={()=>void togglePause()} disabled={saving||loading}>{saving?"Saving…":summary?.pause.active?"Resume AI actions":"Pause AI actions"}</button></header>
 {!navigator.onLine&&<div className="hub-offline" role="status"><CloudOff/> Offline — changes require a secure connection.</div>}{summary?.pause.active&&<div className="hub-pause-state" role="status"><PauseCircle/> AI actions are paused: {summary.pause.reason}</div>}
 <nav aria-label="White-Space Hub sections">{tabs.map(item=><button type="button" key={item} aria-current={selected===item?"page":undefined} onClick={()=>changeTab(item)}>{item}</button>)}</nav>{error&&<div role="alert" className="hub-error"><span>{error}</span><button type="button" onClick={()=>void load()}>Retry</button></div>}
 {loading?<section className="trust-loading" aria-label="Loading Hub data">{Array.from({length:6},(_,i)=><div key={i}/>)}</section>:summary&&selected==="Home"?<section className="trust-summary" aria-label="Live Trust Hub summary">{cards.map(([label,value,target,help,icon])=><button type="button" key={label} onClick={()=>changeTab(target)}>{icon}<span>{label}</span><strong>{value}</strong><small>{value===0?`No ${label.toLowerCase()}`:help}</small></button>)}</section>:summary&&selected==="Safety"&&token?<PolicyFirewall token={token} onChanged={()=>void load()}/>:summary&&selected==="Controls"&&token?<TrustControls token={token} onChanged={()=>void load()}/>:summary&&selected==="Commitments"&&token?<CommitmentEscrow token={token} onChanged={()=>void load()}/>:summary&&selected==="Life Map"&&token?<LifeMap token={token}/>:summary?<OperationalSection tab={selected as Exclude<Tab,"Home">} summary={summary} onNavigate={changeTab}/>:null}
 <footer><span>Data: authenticated server state</span><span>Last sync: {summary?new Date(summary.last_sync).toLocaleString():"Not available"}</span></footer></main>;
}
function OperationalSection({tab,summary,onNavigate}:{tab:Exclude<Tab,"Home">;summary:HubSummary;onNavigate:(tab:Tab)=>void}){const content:Record<Exclude<Tab,"Home">,[string,string,Tab]>={Safety:["Personal Policy Firewall",`${summary.policy_count} policy records`,"Controls"],Controls:["Consent and authority controls",`${summary.active_leases} active leases · ${summary.expiring_leases} expiring`,"Safety"],Commitments:["Commitment Escrow",`${summary.at_risk_commitments} commitments need review`,"Life Map"],"Life Map":["Life Dependency Map","Open commitment dependencies and downstream impact","Commitments"],Evidence:["Action receipts",`${summary.pending_receipts} awaiting evidence · ${summary.blocked_actions} blocked`,"Safety"],Offline:["Offline continuity",navigator.onLine?"Connected — queued actions will be revalidated":"Offline — execution is safely suspended","Controls"]};const [title,detail,target]=content[tab];return <section className="hub-section"><h2>{title}</h2><p>{detail}</p><button type="button" onClick={()=>onNavigate(target)}>Review related controls</button></section>}
