import { useCallback,useEffect,useState } from "react";
import { CheckCircle2,KeyRound,ShieldAlert,XCircle } from "lucide-react";
import { trustHubApi,type AuthoritySetting,type ConsentLease } from "./trustHubApi";
const domains=["alarm","routines","messages","calls","commitments","notifications","offline","security"];
const levels:AuthoritySetting["level"][]=["SUGGEST_ONLY","PREPARE_AND_ASK","EXECUTE_AFTER_CONFIRMATION","EXECUTE_AND_REPORT","BLOCKED"];
export function TrustControls({token,onChanged}:{token:string;onChanged:()=>void}){const [leases,setLeases]=useState<ConsentLease[]>([]),[authority,setAuthority]=useState<AuthoritySetting[]>([]),[error,setError]=useState(""),[creating,setCreating]=useState(false);
 const load=useCallback(async()=>{setError("");try{const [l,a]=await Promise.all([trustHubApi.leases(token),trustHubApi.authorities(token)]);setLeases(l);setAuthority(a)}catch(e){setError(e instanceof Error?e.message:"Controls could not be loaded.")}},[token]);useEffect(()=>{void load()},[load]);
 async function create(form:HTMLFormElement){const data=new FormData(form),days=Number(data.get("days"));try{await trustHubApi.createLease(token,{capability:String(data.get("capability")),purpose:String(data.get("purpose")),fields:data.getAll("fields").map(String),expires_at:new Date(Date.now()+days*86400000).toISOString(),os_permission_granted:false});setCreating(false);await load();onChanged()}catch(e){setError(e instanceof Error?e.message:"Lease could not be requested.")}}
 async function setLevel(domain:string,level:AuthoritySetting["level"]){try{await trustHubApi.setAuthority(token,domain,level);await load()}catch(e){setError(e instanceof Error?e.message:"Authority could not be saved.")}}
 return <section className="trust-controls">{error&&<div className="hub-error" role="alert">{error}<button onClick={()=>void load()}>Retry</button></div>}<section><header><div><h2><KeyRound/> Consent Lease Broker</h2><p>Consent and native permission are enforced separately.</p></div><button onClick={()=>setCreating(true)}>Request lease</button></header>{creating&&<form className="hub-form" onSubmit={e=>{e.preventDefault();void create(e.currentTarget)}}><label>Capability<select name="capability"><option>MICROPHONE</option><option>NOTIFICATIONS</option><option>CONTACTS</option><option>CAMERA</option></select></label><label>Purpose<input name="purpose" minLength={3} required placeholder="Why access is needed"/></label><label>Duration<select name="days"><option value="1">1 day</option><option value="7">7 days</option><option value="30">30 days</option></select></label><label className="hub-check"><input type="checkbox" name="fields" value="basic"/> Basic data only</label><p><ShieldAlert/> Native permission: unsupported in this web session. The lease will remain blocked until the Android permission adapter confirms access.</p><footer><button type="button" onClick={()=>setCreating(false)}>Cancel</button><button type="submit">Save blocked lease</button></footer></form>}<div className="lease-list">{leases.length===0?<p className="hub-empty">No consent leases.</p>:leases.map(lease=><article key={lease.id}><span>{lease.status==="ACTIVE"?<CheckCircle2/>:<XCircle/>}</span><div><strong>{lease.capability}</strong><small>{lease.purpose} · expires {new Date(lease.expires_at).toLocaleString()}</small></div><b>{lease.status.replace(/_/g," ")}</b>{lease.status!=="REVOKED"&&<button onClick={()=>void trustHubApi.revokeLease(token,lease.id).then(()=>{void load();onChanged()})}>Revoke</button>}<button onClick={()=>void trustHubApi.renewLease(token,lease.id,new Date(Date.now()+7*86400000).toISOString()).then(()=>{void load();onChanged()})}>Renew 7 days</button></article>)}</div></section>
 <section><header><div><h2><ShieldAlert/> Authority Gradient</h2><p>Emergency pause and high-risk restrictions always override these settings.</p></div></header><div className="authority-grid">{domains.map(domain=>{const current=authority.find(x=>x.domain===domain)?.level||"EXECUTE_AFTER_CONFIRMATION";return <label key={domain}><span>{domain}</span><select value={current} onChange={e=>void setLevel(domain,e.target.value as AuthoritySetting["level"])}>{levels.map(level=><option key={level} value={level} disabled={["messages","calls","security"].includes(domain)&&level==="EXECUTE_AND_REPORT"}>{level.replace(/_/g," ")}</option>)}</select><small>Effective: {current.replace(/_/g," ")}</small></label>})}</div></section></section>}
