import { createContext } from "react";
import type { PublicCallUser } from "../calls/types";
import type { ScreenShareInvite, ScreenShareQualityMode, ScreenShareRole, ScreenShareSession, ScreenShareSource, ScreenShareUiState } from "./types";

export type ScreenShareContextValue = {
  uiState: ScreenShareUiState;
  role: ScreenShareRole | null;
  session: ScreenShareSession | null;
  requestPeer: PublicCallUser | null;
  inviteOnlyRequest: boolean;
  pendingInvite: ScreenShareInvite | null;
  localStream: MediaStream | null;
  remoteStream: MediaStream | null;
  error: string;
  muted: boolean;
  paused: boolean;
  startedAt: number | null;
  shareCode: string | null;
  canShareScreen: boolean;
  qualityMode: ScreenShareQualityMode;
  networkQuality: "good" | "poor" | "reconnecting" | "unknown";
  sentResolution: string;
  setQualityMode: (mode: ScreenShareQualityMode) => void;
  requestShare: (peer: PublicCallUser) => void;
  cancelRequest: () => void;
  startShare: (source: ScreenShareSource) => Promise<void>;
  generateShareCode: () => Promise<void>;
  joinWithCode: (code: string) => Promise<void>;
  joinInvite: (invite?: ScreenShareInvite | null) => Promise<void>;
  joinInviteLink: (sessionId: string, inviteToken?: string | null) => Promise<void>;
  declineInvite: () => Promise<void>;
  stopShare: () => Promise<void>;
  toggleMute: () => Promise<void>;
  togglePause: () => void;
  copyInviteLink: () => Promise<void>;
  copyShareCode: () => Promise<void>;
  requestInviteShare: () => void;
  clearError: () => void;
};

export const ScreenShareContext = createContext<ScreenShareContextValue | null>(null);
