import { useId, useMemo, useState } from "react";
import { Check, ChevronDown, ChevronUp, Clock3, Cpu, TriangleAlert } from "lucide-react";
import clsx from "clsx";
import type {
  OrchestrationAudit,
  OrchestrationModelAudit,
  OrchestrationTaskStatus
} from "../../types";

const MODE_LABELS: Record<string, string> = {
  instant: "Instant Intelligence",
  medium: "Medium Intelligence",
  high: "High Intelligence",
  deep_research: "Deep Research"
};

type AuditRow = {
  key: string;
  model: string;
  provider: string;
  role: string;
  activity: string;
  status: OrchestrationTaskStatus | "recorded";
  latencyMs?: number;
  contributed: boolean;
};

function providerName(model: OrchestrationModelAudit) {
  if (model.provider_display_name) return model.provider_display_name;
  if (model.provider === "bedrock") return "AWS Bedrock";
  if (model.provider) return model.provider.charAt(0).toUpperCase() + model.provider.slice(1);
  return "AutoAI";
}

function safeStatus(model: OrchestrationModelAudit): AuditRow["status"] {
  if (model.status) return model.status;
  return model.contributed ? "completed" : "recorded";
}

export function responseAuditRows(audit?: OrchestrationAudit | null): AuditRow[] {
  return (audit?.models_consulted ?? []).reduce<AuditRow[]>((rows, model, index) => {
      const displayName = (model.display_name || model.model || "").trim();
      if (!displayName) return rows;
      rows.push({
        key: `${model.provider || "autoai"}:${displayName}:${index}`,
        model: displayName,
        provider: providerName(model),
        role: model.role || "Intelligence contributor",
        activity: model.activity_label || model.role || "Prepared part of the response",
        status: safeStatus(model),
        latencyMs: typeof model.latency_ms === "number" ? model.latency_ms : undefined,
        contributed: Boolean(model.contributed)
      });
      return rows;
    }, []);
}

function statusLabel(status: AuditRow["status"]) {
  if (status === "timed_out") return "Timed out";
  return status.charAt(0).toUpperCase() + status.slice(1);
}

function StatusIcon({ status }: { status: AuditRow["status"] }) {
  if (status === "completed") return <Check size={13} />;
  if (status === "failed" || status === "timed_out") return <TriangleAlert size={13} />;
  return <Cpu size={13} />;
}

export function ResponseGeneratedBy({ audit }: { audit?: OrchestrationAudit | null }) {
  const [open, setOpen] = useState(false);
  const panelId = useId();
  const rows = useMemo(() => responseAuditRows(audit), [audit]);
  if (!rows.length) return null;

  const attempted = audit?.models_attempted ?? rows.length;
  const completed =
    audit?.models_completed ?? rows.filter((row) => row.status === "completed").length;
  const contributed =
    audit?.models_contributed ?? rows.filter((row) => row.contributed).length;
  const generatedBy = Math.max(1, contributed || completed);
  const mode = MODE_LABELS[String(audit?.mode || "")] || "AutoAI Intelligence";

  return (
    <div className="response-audit">
      <button
        className="response-audit-trigger"
        type="button"
        onClick={() => setOpen((value) => !value)}
        aria-expanded={open}
        aria-controls={panelId}
      >
        <Cpu size={12} />
        <span>Response generated by</span>
        <strong>{generatedBy} model{generatedBy === 1 ? "" : "s"}</strong>
        {open ? <ChevronUp size={13} /> : <ChevronDown size={13} />}
      </button>

      {open && (
        <section id={panelId} className="response-audit-log" aria-label="Response generation log">
          <div className="response-audit-summary">
            <span>
              <strong>{mode}</strong>
              {attempted} attempted · {completed} completed · {contributed} used
            </span>
            {typeof audit?.duration_ms === "number" && (
              <span><Clock3 size={12} /> {(audit.duration_ms / 1000).toFixed(1)}s total</span>
            )}
          </div>

          <div className="response-audit-rows">
            {rows.map((row) => (
              <article
                key={row.key}
                className={clsx("response-audit-row", `is-${row.status}`)}
              >
                <div className="response-audit-model">
                  <span className="response-audit-status"><StatusIcon status={row.status} /></span>
                  <span>
                    <strong>{row.model}</strong>
                    <small>{row.provider}</small>
                  </span>
                  <span className="response-audit-state">{statusLabel(row.status)}</span>
                </div>
                <div className="response-audit-work">
                  <span><b>Work</b>{row.role}</span>
                  <span><b>Activity</b>{row.activity}</span>
                </div>
                <div className="response-audit-result">
                  {typeof row.latencyMs === "number" && <span>{(row.latencyMs / 1000).toFixed(1)}s</span>}
                  {row.contributed && <strong>Used in final response</strong>}
                </div>
              </article>
            ))}
          </div>

          {audit?.fallback_used && (
            <p className="response-audit-note">One or more tasks could not finish; AutoAI continued with successful models.</p>
          )}
          {audit?.mode === "deep_research" && (
            <p className="response-audit-note">Verified sources: {audit.verified_sources ?? 0}</p>
          )}
          <p className="response-audit-privacy">Shows safe execution facts only. Private reasoning and prompts are never displayed.</p>
        </section>
      )}
    </div>
  );
}
