import { describe, expect, it } from "vitest";
import type { OrchestrationAudit } from "../../types";
import { responseAuditRows } from "./ResponseGeneratedBy";

describe("response generated by audit", () => {
  it("shows only persisted backend model execution records", () => {
    const audit: OrchestrationAudit = {
      mode: "medium",
      models_consulted: [
        {
          provider: "groq",
          display_name: "GPT-OSS 120B",
          role: "Primary solution generator",
          activity_label: "Preparing the primary answer",
          status: "completed",
          latency_ms: 2100,
          contributed: true
        },
        {
          provider: "groq",
          display_name: "Qwen 3 32B",
          role: "Response organizer",
          activity_label: "Organizing the response",
          status: "timed_out",
          latency_ms: 45000,
          contributed: false
        }
      ]
    };

    expect(responseAuditRows(audit)).toEqual([
      expect.objectContaining({
        model: "GPT-OSS 120B",
        provider: "Groq",
        status: "completed",
        contributed: true
      }),
      expect.objectContaining({
        model: "Qwen 3 32B",
        status: "timed_out",
        contributed: false
      })
    ]);
  });

  it("does not invent a model when no execution record was persisted", () => {
    expect(responseAuditRows({ mode: "instant", models_consulted: [] })).toEqual([]);
  });
});
